Add magento installation command
mittwald/cli pull request #700
Opened 2024-08-13 11:50 UTC by niristius

2024-08-13 11:52 UTC, niristius commented
blocked by https://github.com/mittwald/cli/issues/654

2024-08-22 12:20 UTC, martin-helmich requested changes

2024-08-22 12:20 UTC, martin-helmich commented on src/lib/resources/app/flags.tsx
> +    if (appName.toLowerCase().includes("magento")) {
This seems like a code smell; adding exceptions for special cases in a generic module such as this has the potential to become an unmaintainable mess in the future. Maybe we can add the option to specify default/fallback values in the `AppInstaller` instance, without having to hardcode them in the `buildFlagsWithDescription` function (maybe `buildFlagsWithDescription` could accept the default values as a parameter, which gets passed in from the `AppInstaller`?)

2024-08-28 09:30 UTC, martin-helmich approved these changes

2024-08-28 09:30 UTC, merged