let app and upgrade command accept an AppVersion uuid as target version
mittwald/cli pull request #934
Opened 2024-11-28 14:07 UTC by niristius

this is my implementation to realize the requested feature from https://github.com/mittwald/cli/issues/922

2024-11-28 14:08 UTC, niristius commented
upgrades are included too

2024-12-05 07:45 UTC, martin-helmich requested changes
Some refactoring suggetions; also, mind the linter issues.

2024-12-05 07:45 UTC, martin-helmich commented on src/lib/resources/app/Installer.tsx
> +      appVersion = await normalizeToAppVersionUuid(
Maybe build the "if it looks like a UUID, just use that"-logic directly into `normalizeToAppVersionUuid`? IIRC, all other `normalize<whatever>` functions that we have floating around work more or less similar, anyway.

2024-12-05 07:45 UTC, martin-helmich commented on src/commands/app/upgrade.tsx
> +    ) {
These `AND`ed conditions could be deconstructed to (maybe?) more readable nested conditions:

```
else if (this.flags["target-version"]) {
  if (validateUuid(this.flags["target-version"])) {
    // ...
  } else {
    // ...
  }
} // ...
```

Also, the way how `targetAppVersion` is getting more and more complex, with more and more branches in this condition. I would suggest extracting the entire logic of populating `targetAppVersion` into a function.

2024-12-05 07:47 UTC, merged